
export default new Map([
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/Windows/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FWindows%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Reference/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FReference%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/Security/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FSecurity%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/Settings/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FSettings%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/Security/Sophos Endpoint/captive-portal.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FSecurity%2FSophos+Endpoint%2Fcaptive-portal.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/iCloud/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FiCloud%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/Security/Sophos Endpoint/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FSecurity%2FSophos+Endpoint%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/Guides/iOS and Mac/iCloud/Articles/hide-my-email.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2FGuides%2FiOS+and+Mac%2FiCloud%2FArticles%2Fhide-my-email.mdx&astroContentModuleFlag=true")]]);
		